version: '3.8'

services:
  database:
    image: postgres:15
    container_name: rebill_challenge_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denise2015
      POSTGRES_DB: rebill_challenge_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
